#include <string>
#include <map>
#include "token.h"
#include "util.h"

using namespace std;

const string END_OF_FILE_TOKEN_NAME = "END_OF_FILE";
const string IDENTIFIER_TOKEN_NAME = "IDENTIFIER";
const string INTEGER_TOKEN_NAME = "INTEGER";
const string KEYWORD_BEGIN_TOKEN_NAME = "KEYWORD_BEGIN";
const string KEYWORD_END_TOKEN_NAME = "KEYWORD_END";
const string KEYWORD_CHECK_TOKEN_NAME = "KEYWORD_CHECK";
const string KEYWORD_LOOP_TOKEN_NAME = "KEYWORD_LOOP";
const string KEYWORD_VOID_TOKEN_NAME = "KEYWORD_VOID";
const string KEYWORD_VAR_TOKEN_NAME = "KEYWORD_VAR";
const string KEYWORD_RETURN_TOKEN_NAME = "KEYWORD_RETURN";
const string KEYWORD_INPUT_TOKEN_NAME = "KEYWORD_INPUT";
const string KEYWORD_OUTPUT_TOKEN_NAME = "KEYWORD_OUTPUT";
const string KEYWORD_PROGRAM_TOKEN_NAME = "KEYWORD_PROGRAM";
const string OPERATOR_EQUALS_TOKEN_NAME = "OPERATOR_EQUALS";
const string OPERATOR_LESS_THAN_TOKEN_NAME = "OPERATOR_LESS_THAN";
const string OPERATOR_LESS_THAN_OR_EQUAL_TO_TOKEN_NAME = "OPERATOR_LESS_THAN_OR_EQUAL_TO";
const string OPERATOR_GREATER_THAN_TOKEN_NAME = "OPERATOR_GREATER_THAN";
const string OPERATOR_GREATER_THAN_OR_EQUAL_TO_TOKEN_NAME = "OPERATOR_GREATER_THAN_OR_EQUAL_TO";
const string ILLEGAL_EXCLAMATION_POINT_TOKEN_NAME = "ILLEGAL_EXCLAMATION_POINT";
const string OPERATOR_EXCLAMATION_POINT_EQUALS_TOKEN_NAME = "OPERATOR_EXCLAMATION_POINT_EQUALS";
const string OPERATOR_DOUBLE_EQUALS_TOKEN_NAME = "OPERATOR_DOUBLE_EQUALS";
const string OPERATOR_COLON_TOKEN_NAME = "OPERATOR_COLON";
const string OPERATOR_PLUS_TOKEN_NAME = "OPERATOR_PLUS";
const string OPERATOR_MINUS_TOKEN_NAME = "OPERATOR_MINUS";
const string OPERATOR_ASTERISK_TOKEN_NAME = "OPERATOR_ASTERISK";
const string OPERATOR_FORWARD_SLASH_TOKEN_NAME = "OPERATOR_FORWARD_SLASH";
const string OPERATOR_AMPERSAND_TOKEN_NAME = "OPERATOR_AMPERSAND";
const string OPERATOR_PERCENT_TOKEN_NAME = "OPERATOR_PERCENT";
const string DELIMITER_PERIOD_TOKEN_NAME = "DELIMITER_PERIOD";
const string DELIMITER_LEFT_PARENTHESIS_TOKEN_NAME = "DELIMITER_LEFT_PARENTHESIS";
const string DELIMITER_RIGHT_PARENTHESIS_TOKEN_NAME = "DELIMITER_RIGHT_PARENTHESIS";
const string DELIMITER_LEFT_CURLY_BRACE_TOKEN_NAME = "DELIMITER_LEFT_CURLY_BRACE";
const string DELIMITER_RIGHT_CURLY_BRACE_TOKEN_NAME = "DELIMITER_RIGHT_CURLY_BRACE";
const string DELIMITER_LEFT_SQUARE_BRACKET_TOKEN_NAME = "DELIMITER_LEFT_SQUARE_BRACKET";
const string DELIMITER_RIGHT_SQUARE_BRACKET_TOKEN_NAME = "DELIMITER_RIGHT_SQUARE_BRACKET";
const string DELIMITER_COMMA_TOKEN_NAME = "DELIMITER_COMMA";
const string DELIMITER_SEMICOLON_TOKEN_NAME = "DELIMITER_SEMICOLON";

const map<const TOKEN_IDENTIFIER, const string> TOKEN_IDENTIFIER_TO_TOKEN_NAME_MAP = {
        {END_OF_FILE,                       END_OF_FILE_TOKEN_NAME},
        {IDENTIFIER,                        IDENTIFIER_TOKEN_NAME},
        {INTEGER,                           INTEGER_TOKEN_NAME},
        {KEYWORD_BEGIN,                     KEYWORD_BEGIN_TOKEN_NAME},
        {KEYWORD_END,                       KEYWORD_END_TOKEN_NAME},
        {KEYWORD_CHECK,                     KEYWORD_CHECK_TOKEN_NAME},
        {KEYWORD_LOOP,                      KEYWORD_LOOP_TOKEN_NAME},
        {KEYWORD_VOID,                      KEYWORD_VOID_TOKEN_NAME},
        {KEYWORD_VAR,                       KEYWORD_VAR_TOKEN_NAME},
        {KEYWORD_RETURN,                    KEYWORD_RETURN_TOKEN_NAME},
        {KEYWORD_INPUT,                     KEYWORD_INPUT_TOKEN_NAME},
        {KEYWORD_OUTPUT,                    KEYWORD_OUTPUT_TOKEN_NAME},
        {KEYWORD_PROGRAM,                   KEYWORD_PROGRAM_TOKEN_NAME},
        {OPERATOR_EQUALS,                   OPERATOR_EQUALS_TOKEN_NAME},
        {OPERATOR_LESS_THAN,                OPERATOR_LESS_THAN_TOKEN_NAME},
        {OPERATOR_LESS_THAN_OR_EQUAL_TO,    OPERATOR_LESS_THAN_OR_EQUAL_TO_TOKEN_NAME},
        {OPERATOR_GREATER_THAN,             OPERATOR_GREATER_THAN_TOKEN_NAME},
        {OPERATOR_GREATER_THAN_OR_EQUAL_TO, OPERATOR_GREATER_THAN_OR_EQUAL_TO_TOKEN_NAME},
        {ILLEGAL_EXCLAMATION_POINT,         ILLEGAL_EXCLAMATION_POINT_TOKEN_NAME},
        {OPERATOR_EXCLAMATION_POINT_EQUALS, OPERATOR_EXCLAMATION_POINT_EQUALS_TOKEN_NAME},
        {OPERATOR_DOUBLE_EQUALS,            OPERATOR_DOUBLE_EQUALS_TOKEN_NAME},
        {OPERATOR_COLON,                    OPERATOR_COLON_TOKEN_NAME},
        {OPERATOR_PLUS,                     OPERATOR_PLUS_TOKEN_NAME},
        {OPERATOR_MINUS,                    OPERATOR_MINUS_TOKEN_NAME},
        {OPERATOR_ASTERISK,                 OPERATOR_ASTERISK_TOKEN_NAME},
        {OPERATOR_FORWARD_SLASH,            OPERATOR_FORWARD_SLASH_TOKEN_NAME},
        {OPERATOR_AMPERSAND,                OPERATOR_AMPERSAND_TOKEN_NAME},
        {OPERATOR_PERCENT,                  OPERATOR_PERCENT_TOKEN_NAME},
        {DELIMITER_PERIOD,                  DELIMITER_PERIOD_TOKEN_NAME},
        {DELIMITER_LEFT_PARENTHESIS,        DELIMITER_LEFT_PARENTHESIS_TOKEN_NAME},
        {DELIMITER_RIGHT_PARENTHESIS,       DELIMITER_RIGHT_PARENTHESIS_TOKEN_NAME},
        {DELIMITER_LEFT_CURLY_BRACE,        DELIMITER_LEFT_CURLY_BRACE_TOKEN_NAME},
        {DELIMITER_RIGHT_CURLY_BRACE,       DELIMITER_RIGHT_CURLY_BRACE_TOKEN_NAME},
        {DELIMITER_LEFT_SQUARE_BRACKET,     DELIMITER_LEFT_SQUARE_BRACKET_TOKEN_NAME},
        {DELIMITER_RIGHT_SQUARE_BRACKET,    DELIMITER_RIGHT_SQUARE_BRACKET_TOKEN_NAME},
        {DELIMITER_COMMA,                   DELIMITER_COMMA_TOKEN_NAME},
        {DELIMITER_SEMICOLON,               DELIMITER_SEMICOLON_TOKEN_NAME}
};

const string KEYWORD_LITERAL_BEGIN = "Begin";
const string KEYWORD_LITERAL_END = "End";
const string KEYWORD_LITERAL_CHECK = "Check";
const string KEYWORD_LITERAL_LOOP = "Loop";
const string KEYWORD_LITERAL_VOID = "Void";
const string KEYWORD_LITERAL_VAR = "Var";
const string KEYWORD_LITERAL_RETURN = "Return";
const string KEYWORD_LITERAL_INPUT = "Input";
const string KEYWORD_LITERAL_OUTPUT = "Output";
const string KEYWORD_LITERAL_PROGRAM = "Program";

const map<const string, const TOKEN_IDENTIFIER> KEYWORD_LITERAL_TO_KEYWORD_TOKEN_IDENTIFIER_MAP = {
        {KEYWORD_LITERAL_BEGIN,   KEYWORD_BEGIN},
        {KEYWORD_LITERAL_END,     KEYWORD_END},
        {KEYWORD_LITERAL_CHECK,   KEYWORD_CHECK},
        {KEYWORD_LITERAL_LOOP,    KEYWORD_LOOP},
        {KEYWORD_LITERAL_VOID,    KEYWORD_VOID},
        {KEYWORD_LITERAL_VAR,     KEYWORD_VAR},
        {KEYWORD_LITERAL_RETURN,  KEYWORD_RETURN},
        {KEYWORD_LITERAL_INPUT,   KEYWORD_INPUT},
        {KEYWORD_LITERAL_OUTPUT,  KEYWORD_OUTPUT},
        {KEYWORD_LITERAL_PROGRAM, KEYWORD_PROGRAM},
};

Token::Token(const TOKEN_IDENTIFIER tokenIdentifier, const string value, const string lineNumber) : tokenIdentifier(tokenIdentifier),
                                                                                                    value(value),
                                                                                                    lineNumber(lineNumber) {
}

Token::~Token() = default;

const TOKEN_IDENTIFIER Token::getTokenIdentifier() const {
    return tokenIdentifier;
}

const string &Token::getValue() const {
    return value;
}

const string &Token::getLineNumber() const {
    return lineNumber;
}

const string Token::toString() const {
    return "Line Number: \"" + getLineNumber() + "\", Token Identifier: \"" + TOKEN_IDENTIFIER_TO_TOKEN_NAME_MAP.at(getTokenIdentifier()) + "\", Token Value: \"" + trim(getValue()) + "\"";
}